spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
#    username: batch
#    password: batch
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/app
#    username: root
#    password: root
#    schema: schema-mysql.sql
#    data: data-mysql.sql
#    initialization-mode: always
  batch:
    job:
      names: multi-resource-job
#    initialize-schema: always