spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: batch
    password: batch
  batch:
    job:
      names: listener-job